# @package _group_

# reproducibility
deterministic: True
random_seed: 42

# training

pl_trainer:
  fast_dev_run: False # Enable this for debug purposes
  gpus: 0
  precision: 32
  max_epochs: 1000
  check_val_every_n_epoch: 10
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  automatic_optimization: False
  track_grad_norm: 2

monitor_metric: 'metaval/outer_accuracy'
monitor_metric_mode: 'max'


model_checkpoints:
  save_top_k: 3
  verbose: True
